use MisToimub;

DROP PROCEDURE IF EXISTS TEST_CLEANUP;

DELIMITER //
CREATE PROCEDURE TEST_CLEANUP ()
BEGIN
    UPDATE User SET deleteDate=NULL WHERE ID=1 AND email='test@test.ee';
	DELETE FROM User WHERE OrganizationID=1 AND ID>1;
  	UPDATE Event SET deleteDate=NULL WHERE ID=1 AND OrganizationID=1;
  	DELETE FROM Event WHERE OrganizationID=1 AND ID>1;
END//
DELIMITER ;

CALL TEST_CLEANUP;